version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v3.9.1
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - monitoring_data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.4.0-22081664032
    ports:
      - "3000:3000"
    volumes:
      - monitoring_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  k6:
    image: grafana/k6:1.6.1
    volumes:
      - ./tests:/scripts
    command: run /scripts/test.js

volumes:
  monitoring_data:
